services:
  perception:
    build: .
    container_name: shobo-perception
    restart: unless-stopped
    network_mode: host
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - RGB_DEV=/dev/video1         # adjust if your RGB UVC is a different node
      - IR_SENSOR_ID=0              # IMX219 on CSI sensor index
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./ros2_ws/yolov8n.engine:/work/ros2_ws/yolov8n.engine:ro
  engine:
    build:
      context: .
      dockerfile: tools/Dockerfile.engine
    container_name: shobo-engine
    runtime: nvidia
    gpus: all
    network_mode: host
    environment:
      - YOLO_CONFIG_DIR=/work/.ultralytics
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - .:/work
      - ./ros2_ws:/work/ros2_ws           # save engine here
      - ./tools:/work/tools:ro            # exporter script
    working_dir: /work
