services:
  perception:
    build:
      context: .
      args:
        L4T_TAG: r36.4.0
    container_name: shobo-perception
    restart: unless-stopped
    network_mode: host
    runtime: nvidia
    privileged: true
    ipc: host
    user: "0:0"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - RGB_DEV=/dev/video1
      - IR_SENSOR_ID=0
      - ROS_DISTRO=humble
      # Make sure runtime can find Jetson & CUDA libs:
      - LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/tegra:/usr/local/cuda/targets/aarch64-linux/lib
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/argus_socket:/tmp/argus_socket
      # Mount config only; TensorRT engine is regenerated inside the container
      - ./ros2_ws/yolov8n.json:/work/ros2_ws/yolov8n.json:ro
    group_add:
      - "44" # video
    profiles: ["perception"] 

  engine:
    build:
      context: .
      dockerfile: tools/Dockerfile.engine
    container_name: shobo-engine
    runtime: nvidia
    gpus: all
    network_mode: host
    environment:
      - YOLO_CONFIG_DIR=/work/.ultralytics
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - .:/work
      - ./ros2_ws:/work/ros2_ws
      - ./tools:/work/tools:ro
    working_dir: /work
    profiles: ["engine-builder"]
  
# ====================== INFRA (Foxglove bridge / WS) ======================
  infra:
    container_name: shobo-infra
    build:
      context: ./infra
    image: shobo-infra:latest
    network_mode: host
    ipc: host
    restart: unless-stopped
    environment:
      ROS_DOMAIN_ID: "0"
      FOXGLOVE_PORT: "${FOXGLOVE_PORT:-8765}"
      FOXGLOVE_ADDRESS: "0.0.0.0"
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 ${FOXGLOVE_PORT:-8765}"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 5s
    command: ["/start.sh"]
    profiles: ["infra"]
