services:
  perception:
    build:
      context: .
      args:
        L4T_TAG: r36.4.0   # closest published tag to your R36.4.4
    container_name: shobo-perception
    restart: unless-stopped
    network_mode: host
    runtime: nvidia
    privileged: true                  # needed for CSI (IMX219) access
    ipc: host
    user: "0:0"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - RGB_DEV=/dev/video1           # adjust if your RGB UVC is a different node
      - IR_SENSOR_ID=0                # IMX219 on CSI sensor index
      - ROS_DISTRO=humble
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/argus_socket:/tmp/argus_socket    # CSI camera daemon socket
      - ./ros2_ws/yolov8n.engine:/work/ros2_ws/yolov8n.engine:ro
      - ./ros2_ws/yolov8n.json:/work/ros2_ws/yolov8n.json:ro
      - ./ros2_ws:/work/ros2_ws                # lets you rebuild in-container if needed
    group_add:
      - "44" # video

  engine:
    build:
      context: .
      dockerfile: tools/Dockerfile.engine
    container_name: shobo-engine
    runtime: nvidia
    gpus: all
    network_mode: host
    environment:
      - YOLO_CONFIG_DIR=/work/.ultralytics
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - .:/work
      - ./ros2_ws:/work/ros2_ws           # save engine here
      - ./tools:/work/tools:ro            # exporter script
    working_dir: /work
    profiles: ["engine-builder"]   # 👈 only runs if explicitly requested