shobo_sensors:
  ros__parameters:
    ir:
      sensor_id: "$(env IR_SENSOR_ID 0)"
      width: 1280
      height: 720
      fps: 30
      frame_id: "ir_frame"
      camera_name: "ir_imx219"
      camera_info_url: ""

      use_gst: true
      gst_pipeline: >
        nvarguscamerasrc sensor-id=$(env IR_SENSOR_ID 0) !
        video/x-raw(memory:NVMM),width=1280,height=720,framerate=30/1 !
        nvvidconv !
        video/x-raw,format=BGRx !
        videoconvert !
        video/x-raw,format=BGR !
        appsink drop=true max-buffers=1 sync=false
