ir_cam:
  ros__parameters:
    'ir.sensor_id': 0
    'ir.width': 640
    'ir.height': 640
    'ir.fps': 30
    'ir.frame_id': "ir_frame"
    'ir.camera_name': "ir_imx219"
    'ir.camera_info_url': "package://shobo_bringup/config/camera_info/ir_imx219.yaml"
