rgb_cam:
  ros__parameters:
    'rgb.device': "/dev/video1"
    'rgb.width': 1280
    'rgb.height': 720
    'rgb.fps': 30
    'rgb.frame_id': "rgb_frame"
    'rgb.camera_name': "rgb_uvc"
    'rgb.camera_info_url': "package://shobo_bringup/config/camera_info/rgb_uvc.yaml"
